variables:
  GIT_DEPTH: 0

stages:
  - preparation
  - build
  - release
  - package

include:
  - remote: "https://api.r2devops.io/job/r/r2devops-bot/gitleaks/1.0.0.yaml"
  - remote: "https://api.r2devops.io/job/r/r2devops-bot/docker_build/1.1.0.yaml"
  # - remote: "https://api.r2devops.io/job/r/r2devops-bot/spell_check/1.0.0.yaml" // wait for the fix from r2devops

gitleaks:
  stage: .pre

determine_version:
  stage: preparation
  image:
    name: "gittools/gitversion:5.10.0-alpine.3.14-6.0"
    entrypoint: [""]
  script: |
    echo "Determining version..."
    echo "GIT_DEPTH: ${GIT_DEPTH}"

    if [[ -z "${CI_COMMIT_TAG}" ]]; then
      echo "MajorMinorPatch: $(/tools/dotnet-gitversion /showvariable MajorMinorPatch)"
      /tools/dotnet-gitversion /showvariable MajorMinorPatch > SemVer.txt
      echo "-rc" >> SemVer.txt
      /tools/dotnet-gitversion /showvariable CommitsSinceVersionSource >> SemVer.txt
      echo "." >> SemVer.txt
      /tools/dotnet-gitversion /showvariable EscapedBranchName >> SemVer.txt
      echo "." >> SemVer.txt
      /tools/dotnet-gitversion /showvariable ShortSha >> SemVer.txt
    else
      echo "CommitTag: ${CI_COMMIT_TAG}"
      echo "${CI_COMMIT_TAG}" | tr -d 'v' | tr -d '\n\r' | cat > SemVer.txt
    fi

    echo "BUILD_VERSION=$(cat SemVer.txt | tr -d '\n\r' | cat)" > build.env
    echo "BUILD_DATE=$(date)" >> build.env
    echo "BUILD_HASH=$(git rev-parse --short HEAD)" >> build.env
    echo "BUILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> build.env
    echo "BUILD_TAG=$(git describe --tags)" >> build.env
    cat build.env
  artifacts:
    reports:
      dotenv: build.env

docker_build:
  variables:
    CUSTOM_TAG: ${BUILD_VERSION}

.git_push: &git_push
  before_script:
    - apt-get update -y && apt-get install -yqqf openssh-client git unzip sshpass rsync --fix-missing
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $CI_SERVER_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - git config user.name "polycode.bot"
    - git config user.email "bot@polycode.do-2021.fr"
  after_script:
    - eval $(ssh-agent -s)
    - echo "$GITLAB_GIT_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - git pull "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git" ${CI_COMMIT_BRANCH:-main} --rebase --autostash -Xours
    - git commit -a -m "${GIT_PUSH_COMMIT_NAME}"
    - git push "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git" HEAD:${CI_COMMIT_BRANCH:-main}

bump_version:
  stage: release
  image: node:16-buster-slim
  only:
    - main
    - tags
  variables:
    GIT_PUSH_COMMIT_NAME: "chore: bump app version to ${BUILD_VERSION} [skip ci]"
  <<: *git_push
  script: |
    echo "VERSION=$BUILD_VERSION"

    sed -i "/\"version\":/c\  \"version\": \"$BUILD_VERSION\"," package.json
    sed -i "/appVersion:/c\appVersion: \'$BUILD_VERSION\'" ./helm/chart/Chart.yaml
    sed -i "/version:/c\version: \'$BUILD_VERSION\'" ./helm/chart/Chart.yaml

    if [[ ! -z "${CI_COMMIT_TAG}" ]]; then
      npm install -g conventional-changelog-cli
      conventional-changelog -p angular -i CHANGELOG.md -s
    fi

helm-package:
  stage: package
  image:
    name: alpine/helm:3.5.3
    entrypoint: ['']
  variables:
    CHART: frontend
    CI_REGISTRY_USER: gitlab-ci-token
    CI_REGISTRY_PASSWORD: ${CI_JOB_TOKEN}
  before_script:
    - apk add git
    - helm plugin install --version=v0.10.2 https://github.com/chartmuseum/helm-push.git
    - >
      helm repo add ${CHART}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script: |
    sed -i "/appVersion:/c\appVersion: \'$BUILD_VERSION\'" ${CI_PROJECT_DIR}/helm/chart/Chart.yaml
    sed -i "/version:/c\version: \'$BUILD_VERSION\'" ${CI_PROJECT_DIR}/helm/chart/Chart.yaml
    helm package ${CI_PROJECT_DIR}/helm/chart
    helm cm-push ${CI_PROJECT_DIR}/${CHART}-${BUILD_VERSION}.tgz ${CHART}
